# Generated by Django 4.0.6 on 2023-07-25 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_cartitem_final_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='quantity_needed_for_discount',
            new_name='quantity_threshold',
        ),
        migrations.AlterField(
            model_name='discount',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='base.product'),
        ),
    ]
